forest/urls.py
import django.contrib.auth.views
import django.views.static
import forest.main.views as views

from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = [
    url(r'^_epub/$', views.EpubExporterView.as_view()),

    url('^accounts/', include('djangowind.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^_impersonate/', include('impersonate.urls')),
    url(r'^pagetree/', include('pagetree.urls')),
    url(r'^logout/$', django.contrib.auth.views.logout, {'next_page': '/'}),
    url(r'^uploads/(?P<path>.*)$', django.views.static.serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^_stand/$', views.EditStandView.as_view()),
    url(r'^_stand/add/$', views.AddStandView.as_view()),
    url(r'^_stand/users/$', views.StandUsersView.as_view()),
    url(r'^_stand/users/(?P<id>\d+)/$', views.EditStandUserView.as_view()),
    url(r'^_stand/users/add/$', views.StandAddUserView.as_view()),
    url(r'^_stand/users/(?P<pk>\d+)/delete/$',
        views.DeleteStandUserView.as_view()),
    url(r'^_stand/groups/$', views.StandGroupsView.as_view()),
    url(r'^_stand/groups/add/$', views.StandAddGroupView.as_view()),
    url(r'^_stand/groups/(?P<id>\d+)/$', views.EditStandGroupView.as_view()),
    url(r'^_stand/groups/(?P<pk>\d+)/delete/$',
        views.DeleteStandGroupView.as_view()),
    url(r'^_stand/blocks/$', views.ManageBlocksView.as_view()),
    url(r'^_stand/css/$', views.CSSView.as_view()),
    url(r'^_stand/delete/$', views.DeleteStandView.as_view()),
    url(r'^_stand/clone/$', views.ClonerView.as_view()),
    url(r'^_quiz/', include('quizblock.urls')),
    url(r'^_likert/', include('likertblock.urls')),
    url(r'^_careermap/', include('careermapblock.urls')),
    url(r'^_fridge/', include('fridgeblock.urls')),
    url('_smoketest/', include('smoketest.urls')),
    url(r'^_stats/$', TemplateView.as_view(template_name="main/stats.html")),
    url(r'^edit/(?P<path>.*)$', views.EditView.as_view(), {}, 'edit-page'),
    url(r'^instructor/(?P<path>.*)$', views.InstructorView.as_view()),
    url(r'^(?P<path>.*)$', views.PageView.as_view()),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

forest/main/models.py
from django.db import models
from django.contrib.auth.models import User, Group
import hashlib
from django.apps import apps
from django.conf import settings
from pagetree.helpers import get_section_from_path

from .auth import AccessChecker


class Stand(models.Model):
    title = models.CharField(max_length=256, default=u"", blank=True,
                             null=True)
    hostname = models.CharField(max_length=256, db_index=True, blank=False)
    created = models.DateTimeField(auto_now=True)
    css = models.TextField(default=u"", blank=True, null=True)
    description = models.TextField(default=u"", blank=True, null=True)

    ACCESS_CHOICES = (('open', 'Open Access'),
                      ('login', 'Logged-in Users Only'),
                      ('group', 'Users in Selected Group(s) Only'),
                      ('whitelist', 'Whitelisted Users Only'))
    access = models.CharField(max_length=256, default="open",
                              choices=ACCESS_CHOICES)
    gated = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title

    def css_hash(self):
        sha1 = hashlib.sha1()
        sha1.update(self.css)
        return sha1.hexdigest()

    def can_edit(self, user):
        return AccessChecker(self, user).can_edit()

    def can_view(self, user):
        return AccessChecker(self, user).can_view()

    def can_admin(self, user):
        return AccessChecker(self, user).can_admin()

    def available_pageblocks(self):
        enabled = [pb.block for pb in self.standavailablepageblock_set.all()]
        return [apps.get_model(*pb.split('.')) for pb in settings.PAGEBLOCKS
                if pb in enabled]

    def get_root(self):
        """ return the Root pagetree.Section for this Stand """
        section = get_section_from_path("/", hierarchy=self.hostname)
        return section.hierarchy.get_root()

    def get_hierarchy(self):
        return get_section_from_path("/", hierarchy=self.hostname).hierarchy

    def make_default_tree(self):
        """ when a new stand is created, we want to populate it
        with at least one Section and a bit of content to get things
        started so the user isn't just presented with a blank page"""
        self.get_root().add_child_section_from_dict(
            {
                'label': 'Welcome',
                'slug': 'welcome',
                'pageblocks': [
                    {'label': 'Welcome to your new Forest Site',
                     'css_extra': '',
                     'block_type': 'Text Block',
                     'body': 'You should now use the edit link to add content',
                     },
                ],
                'children': [],
            })


class StandUser(models.Model):
    stand = models.ForeignKey(Stand)
    user = models.ForeignKey(User)
    access = models.CharField(max_length=16, default="student")

    class Meta:
        ordering = ('user__last_name', 'user__first_name')


class StandGroup(models.Model):
    stand = models.ForeignKey(Stand)
    group = models.ForeignKey(Group)
    access = models.CharField(max_length=16, default="student")


class StandSetting(models.Model):
    stand = models.ForeignKey(Stand)
    name = models.CharField(max_length=256, db_index=True)
    value = models.CharField(max_length=256)


class StandAvailablePageBlock(models.Model):
    stand = models.ForeignKey(Stand)
    block = models.CharField(max_length=256, db_index=True)


def get_stand(hostname, user=None):
    r = Stand.objects.filter(hostname=hostname)
    if r.count() > 0:
        return r[0]
    return None

forest/main/forms.py
from models import Stand
from django.forms import ModelForm


class StandForm(ModelForm):
    class Meta:
        model = Stand
        exclude = []

forest/main/views.py
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from django.template.loader import render_to_string
from django.views.generic.base import View
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from pagetree.helpers import get_section_from_path
from pagetree.generic.views import PageView as GenericPageView
from pagetree.generic.views import InstructorView as GenericInstructorView
from pagetree.generic.views import EditView as GenericEditView
from django.contrib.auth.decorators import login_required
from epubbuilder import epub
from forest.main.models import get_stand, Stand
from forest.main.models import StandUser, User, Group, StandGroup
from forest.main.models import StandAvailablePageBlock
from forest.main.forms import StandForm
from pagetree.models import PageBlock
import os
from django.shortcuts import render


def context_processor(request):
    return dict(MEDIA_URL=settings.MEDIA_URL)


def permission_denied(request, message=""):
    return render(request, "403.html",
                  context=dict(message=message), status=403)


class StandMixin(object):
    def dispatch(self, *args, **kwargs):
        stand = get_stand(self.request.get_host())
        if not stand:
            return HttpResponse("no such site '%s'" % self.request.get_host())
        self.request.stand = stand
        return super(StandMixin, self).dispatch(*args, **kwargs)


class StandAdminMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        stand = get_stand(self.request.get_host())
        if not stand:
            return HttpResponse("no such site '%s'" % self.request.get_host())
        if not stand.can_admin(self.request.user):
            return permission_denied(
                self.request,
                "You do not have admin permission.")
        self.request.stand = stand
        return super(StandAdminMixin, self).dispatch(*args, **kwargs)


class LoggedInMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoggedInMixin, self).dispatch(*args, **kwargs)


class PageView(StandMixin, GenericPageView):
    no_root_fallback_url = "/_stand/"

    def get_gated(self):
        return self.request.stand.gated

    def get_extra_context(self):
        context = super(PageView, self).get_extra_context()
        can_edit = self.request.stand.can_edit(self.request.user)
        can_admin = self.request.stand.can_admin(self.request.user)
        context.update(
            dict(
                stand=self.request.stand,
                can_edit=can_edit,
                can_admin=can_admin))
        return context

    def get_section(self, path):
        hierarchy = self.request.get_host()
        return get_section_from_path(
            path,
            hierarchy_name=hierarchy,
            hierarchy_base="/")

    def perform_checks(self, request, path):
        if not request.stand.can_view(request.user):
            if not request.user.is_anonymous:
                return permission_denied(request)
            return HttpResponseRedirect("/accounts/login/?next=/")
        if (request.stand.gated and
                request.user.is_anonymous):
            return HttpResponseRedirect("/accounts/login/?next=/")
        return super(PageView, self).perform_checks(request, path)


class InstructorView(LoggedInMixin, StandMixin, GenericInstructorView):
    def perform_checks(self, request, path):
        if not request.stand.can_view(request.user):
            if not request.user.is_anonymous:
                return permission_denied(request)
            return HttpResponseRedirect("/accounts/login/?next=/")
        return super(InstructorView, self).perform_checks(request, path)

    def get_section(self, path):
        hierarchy = self.request.get_host()
        return get_section_from_path(
            path,
            hierarchy_name=hierarchy,
            hierarchy_base="/")

    def get_extra_context(self):
        context = super(InstructorView, self).get_extra_context()
        context.update(dict(stand=self.request.stand))
        return context


class EditView(LoggedInMixin, StandMixin, GenericEditView):
    def perform_checks(self, request, path):
        if not request.stand.can_edit(request.user):
            return permission_denied(request,
                                     "You are not an admin for this site")
        return super(EditView, self).perform_checks(request, path)

    def get_section(self, path):
        hierarchy = self.request.get_host()
        return get_section_from_path(
            path,
            hierarchy_name=hierarchy,
            hierarchy_base="/")

    def get_extra_context(self):
        context = super(EditView, self).get_extra_context()
        can_admin = self.request.stand.can_admin(self.request.user)
        context.update(
            dict(
                stand=self.request.stand,
                can_admin=can_admin,
                available_pageblocks=self.request.stand.available_pageblocks(),
            ))
        return context


class CSSView(StandMixin, View):
    def get(self, request):
        return HttpResponse(request.stand.css, content_type="text/css")


class EditStandView(StandAdminMixin, View):
    template_name = 'main/edit_stand.html'

    def post(self, request):
        form = StandForm(request.POST, instance=request.stand)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect("/_stand/")

    def get(self, request):
        is_seed_stand = (request.stand.hostname == settings.SEED_STAND)
        return render(
            request, self.template_name,
            dict(stand=request.stand,
                 form=StandForm(instance=request.stand),
                 is_seed_stand=is_seed_stand))


default_css = """
#header { background: #262; }
"""


class AddStandView(LoggedInMixin, View):
    template_name = "main/add_stand.html"

    def post(self, request):
        if not request.user.is_staff:
            return HttpResponse("only staff may access this")
        form = StandForm()
        form = StandForm(request.POST)
        hostname = request.POST.get('hostname', '')
        r = Stand.objects.filter(hostname=hostname)
        if r.count() > 0:
            return HttpResponse("a stand with that hostname already exists")
        if form.is_valid():
            stand = form.save()
            su = StandUser.objects.create(stand=stand, user=request.user,
                                          access="admin")
            for pb in settings.PAGEBLOCKS:
                StandAvailablePageBlock.objects.create(stand=stand,
                                                       block=pb)
            stand.make_default_tree()
            if hostname.endswith(".forest.ccnmtl.columbia.edu"):
                # if it's a *.forest site, just send them on their way
                return HttpResponseRedirect("http://%s/_stand/" % hostname)
            else:
                return render(request, self.template_name,
                              dict(created=True, stand=stand, su=su))
        return render(request, self.template_name, dict(form=form))

    def get(self, request):
        if not request.user.is_staff:
            return HttpResponse("only staff may access this")
        form = StandForm()
        form = StandForm(request.POST)
        return render(request, self.template_name, dict(form=form))


class DeleteStandView(StandAdminMixin, View):
    def post(self, request):
        request.stand.get_root().hierarchy.delete()
        request.stand.get_root().delete()
        request.stand.delete()
        return HttpResponse("""Stand has been deleted. Thank you""")

    def get(self, request):
        return HttpResponse("""
<form action="." method="post">
Are you sure? <input type="submit" value="YES!" />
</form>
""")


class StandAddUserView(StandAdminMixin, View):
    def post(self, request):
        username = request.POST.get(
            'user', request.POST.get('uni', ''))
        try:
            u = User.objects.get(username=username)
        except User.DoesNotExist:
            if username == "":
                return HttpResponse("no username or uni specified")
            u = User(username=username, password='forest user')
            u.set_unusable_password()
            u.email = u.username + "@columbia.edu"
            u.save()
        r = StandUser.objects.filter(stand=request.stand, user=u)
        if r.count() > 0:
            # if that user already exists, redirect them to the standuser page
            # so they can just edit the access level, which is what they
            # probably want
            return HttpResponseRedirect("/_stand/users/%d/" % r[0].id)
        access = request.POST.get('access')
        StandUser.objects.create(stand=request.stand, user=u,
                                 access=access)
        return HttpResponseRedirect("/_stand/users/")


class EditStandUserView(StandAdminMixin, View):
    template_name = "main/edit_stand_user.html"

    def post(self, request, id):
        standuser = StandUser.objects.get(id=id)
        standuser.access = request.POST.get("access", "student")
        standuser.save()
        return HttpResponseRedirect("/_stand/users/")

    def get(self, request, id):
        standuser = StandUser.objects.get(id=id)
        return render(request, self.template_name,
                      dict(standuser=standuser))


class DeleteStandUserView(StandAdminMixin, DeleteView):
    model = StandUser
    success_url = "/_stand/users/"


class StandUsersView(StandAdminMixin, ListView):
    template_name = "main/stand_users.html"
    model = User
    context_object_name = "all_users"


class StandAddGroupView(StandAdminMixin, View):
    def post(self, request):

forest/templates/main/add_stand.html
{% extends 'base.html' %}
{% block title %}Add Stand{% endblock %}
{% block content %}
{% if created %}
<p>Your new stand has been created, but may not be accessible yet. 
  You can either wait for the DNS registration to complete, or you can modify your /etc/hosts and
  then click <a href="//{{stand.hostname}}/_stand/">here</a> to begin configuring and adding content.</p>
<p>See <a href="http://support.apple.com/kb/TA27291">Apple's
    instructions for doing this on OS X</a> [insert Windows
    instructions here?]</p>
{% else %}
<h2>Create a new Stand</h2>
<form action="." method="post">
<table>
{{form.as_table}}
</table>
<input type="submit" value="add" />
</form>
{% endif %}
{% endblock %}

forest/templates/main/clone.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
  <p>
    Clone to what hostname?
    <input type="text" name="new_hierarchy" />
  </p>
  <p>
    Copy user permissions?
    <input type="checkbox" name="copy_userperms" />
  </p>
  <input type="submit" value="Clone it!" />
</form>

<div class="alert"><b>Warning!</b>
Cloning is still a bit rough around the edges. In particular, uploaded
assets like images don't actually get cloned. So be prepared to do a
bit of cleanup on the newly cloned site.</div>


{% endblock %}

forest/templates/main/edit_stand.html
{% extends 'base.html' %}
{% load waffle_tags %}
{% load bootstrap %}
{% block title %}Edit Stand{% endblock %}
{% block content %}
<form action="." method="post" class="well form-horizontal">

<h1>Edit Stand</h1>


{{form|bootstrap}}

<input type="submit" value="save" class="btn btn-primary" />

</form>
<p><a href="users/">Manage users</a></p>
<p><a href="groups/">Manage groups</a></p>
<p><a href="blocks/">Manage Available Pageblocks</a></p>
<p><a href="clone/">Clone this Stand</a></p>
<p>Or go to the <a href="/edit/">Page edit interface</a></p>

{% if is_seed_stand %}<p>you can also <a href="add/">create a new Stand</a></p>{% endif %}

{% flag 'epub' %}
<h3>Download EPUB</h3>
<div class="alert"><b>Warning!</b> This is still highly
experimental and currently, only
text blocks are supported. There are also known issues
with sites that have duplicate section titles. Use
at your own risk.</div>

<a href="/_epub/" class="btn">Download EPUB</a>

<hr />
{% endflag %}

<ul>Coming soon:
<li>flatpages</li>
<li>track user progress (and admin/instructor view)</li>
</ul>

<p><a href="delete/" class="btn btn-danger" >Delete this Stand</a></p>

<br />
<br />

{% endblock %}

			{% block navrightextra %}
<li><a href="/" class="btn-success">View Site</a></li>
			{% endblock %}

forest/templates/main/edit_stand_group.html
{% extends 'base.html' %}
{% block title %}Edit Group{% endblock %}
{% block content %}

<h1>Group: {{standgroup.group.name}}</h1>

<form action="." method="post" class="well form-inline">

<label>Access Level:
<select name="access">
<option value="student"{% ifequal standgroup.access 'student' %}
	selected="selected"{% endifequal %}>student</option>
<option value="instructor"{% ifequal standgroup.access 'instructor' %}
	selected="selected"{% endifequal %}>instructor</option>
<option value="admin"{% ifequal standgroup.access 'admin' %}
	selected="selected"{% endifequal %}>admin</option>
</select>
</label>

<input type="submit" value="save" class="btn btn-primary"/>
</form>

<form action="delete/" method="post" class="well">
<input type="submit" value="delete" class="btn btn-danger"/>
</form>
{% endblock %}

forest/templates/main/edit_stand_user.html
{% extends 'base.html' %}
{% block title %}Edit User{% endblock %}
{% block content %}
<h1>User: 
{% if standuser.user.first_name %}
{{standuser.user.last_name}}, {{standuser.user.first_name}} 
({{standuser.user.username}})
{% else %}
{{standuser.user.username}}
{% endif %}</h1>

<form action="." method="post" class="well form-inline">
<label>Access Level:
<select name="access">
<option value="student"{% ifequal standuser.access 'student' %}
	selected="selected"{% endifequal %}>student</option>
<option value="instructor"{% ifequal standuser.access 'instructor' %}
	selected="selected"{% endifequal %}>instructor</option>
<option value="admin"{% ifequal standuser.access 'admin' %}
	selected="selected"{% endifequal %}>admin</option>
</select></label>
<input type="submit" value="save" class="btn btn-primary" />
</form>


<form action="delete/" method="post" class="well">
<input type="submit" value="delete" class="btn btn-danger" />
</form>
{% endblock %}

forest/templates/main/import.html
{% extends "base.html" %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
  <input type="file" name="file" />
  <input type="submit" value="Import from ZIP" />
</form>
{% endblock %}

forest/templates/main/manage_blocks.html
{% extends 'base.html' %}

{% block title %}Manage Blocks{% endblock %}
{% block content %}
<form action="." method="post" class="well">
<fieldset>
    <legend>Manage PageBlock Availability</legend>

{% for block in all_blocks %}
<div class="control-group">
      
        <label class="checkbox"><input type="checkbox" class="input-xlarge" 
							 name="{{block.name}}"
							 {% if block.enabled %}checked{% endif %}
							 >
				{{block.name}}</label>
    </div>

{% endfor %}


<input type="submit" value="save" class="btn btn-primary" />
</fieldset>
</form>
{% endblock %}

forest/templates/main/stand_groups.html
{% extends 'base.html' %}
{% block title %}Groups{% endblock %}
{% block content %}
<h1>Groups</h1>
<h2>Add Group</h2>
<form action="add/" method="post" class="well" >
<table>
<tr>
<td>
<b>Select existing group</b><br />
<select name="group">
<option value="" selected="selected">Select existing group</option>
{% for g in all_groups %}
<option value="{{g.id}}">{{g.name}}</option>
{% endfor %}
</select></td>
<td>
<b>access level</b><br />
<select name="access">
<option value="student">student</option>
<option value="instructor">instructor</option>
<option value="admin">admin</option>
</select></td>
<td>
<input type="submit" value="add" class="btn btn-primary" />
</td></tr>
</table>
</form>

{% if stand.standgroup_set.count %}
<h2>Existing Groups</h2>
<table class="table-striped table-bordered">
	<thead>
		<tr>
			<th>group</th>
			<th>access level</th>
		</tr>
	</thead>
	<tbody>
{% for standgroup in stand.standgroup_set.all %}
<tr>
<th>
<a href="{{standgroup.id}}/">{{standgroup.group.name}}</a>
</th>
<td>{{standgroup.access}}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}

{% endblock %}

forest/templates/main/stand_users.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %}Users{% endblock %}
{% block content %}
<h1>Users</h1>
<h2>Add User</h2>
<form action="add/" method="post" class="well form-inline">
<table>
<tr>
<td>
<b>Select existing user</b><br />
<select name="user">
<option value="" selected="selected">Select existing user</option>
<option value="">or Add by UNI</option>
{% for u in all_users %}
<option value="{{u.username}}">{{u.last_name}}, {{u.first_name}} ({{u.username}})</option>
{% endfor %}
</select></td>
<td>
<b>or enter UNI</b><br />
<input type="text" size="5" name="uni" />
<td>
<b>access level</b><br />
<select name="access">
<option value="student">student</option>
<option value="instructor">instructor</option>
<option value="admin">admin</option>
</select></td>
<td>
<input type="submit" value="add" class="btn btn-primary" />
</td></tr>
</table>
</form>


{% if stand.standuser_set.count %}
<h2>Existing Users</h2>
<table class="table-striped table-bordered">
	<thead>
		<tr>
			<th>User</th>
			<th>Access Level</th>
		</tr>
	</thead>
	<tbody>
{% for standuser in stand.standuser_set.all %}
<tr class="{% cycle 'even' 'odd' %}">
<th>
<a href="{{standuser.id}}/">{% if standuser.user.first_name %}
{{standuser.user.last_name}}, {{standuser.user.first_name}} 
({{standuser.user.username}})
{% else %}
{{standuser.user.username}}
{% endif %}</a>
</th>
<td>{{standuser.access}}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}
{% endblock %}